import type { IndicatorDomainDefinition } from "@/lib/indicator-framework/types";

/** Canonical domain catalog — 22 indicator domains. */
export const INDICATOR_DOMAIN_CATALOG: readonly IndicatorDomainDefinition[] = [
  {
    id: "governance",
    slug: "governance",
    title: "Governance",
    purpose: "Measure institutional governance using verifiable public records.",
    scope: "Countries, government institutions, and public entities.",
    evidenceExpectations:
      "Constitutional texts, election records, administrative structure datasets.",
    futureExpansion: "Subnational governance and regulatory agency indicators.",
  },
  {
    id: "economy",
    slug: "economy",
    title: "Economy",
    purpose: "Describe macroeconomic conditions from official statistics.",
    scope: "Countries and economic sectors.",
    evidenceExpectations: "National accounts, inflation, GDP, fiscal balance data.",
    futureExpansion: "Regional economic comparison and sector decomposition.",
  },
  {
    id: "human-rights",
    slug: "human-rights",
    title: "Human Rights",
    purpose: "Track human-rights-related evidence from verified datasets.",
    scope: "Countries and institutions under international reporting.",
    evidenceExpectations:
      "Treaty body reports, UN mechanisms, independently verified indices.",
    futureExpansion: "Civil liberties event datasets with full attribution.",
  },
  {
    id: "education",
    slug: "education",
    title: "Education",
    purpose: "Assess education system evidence from accreditation and statistics.",
    scope: "Countries, universities, and education institutions.",
    evidenceExpectations: "Enrollment, literacy, accreditation, program catalogs.",
    futureExpansion: "Learning outcome indicators with source provenance.",
  },
  {
    id: "research",
    slug: "research",
    title: "Research",
    purpose: "Document research capability from bibliometric and grant sources.",
    scope: "Universities, research centers, and countries.",
    evidenceExpectations: "Publication indexes, grant databases, R&D expenditure.",
    futureExpansion: "Field-normalized research output indicators.",
  },
  {
    id: "innovation",
    slug: "innovation",
    title: "Innovation",
    purpose: "Capture innovation ecosystem evidence without market hype.",
    scope: "Countries, companies, universities.",
    evidenceExpectations: "Patent filings, R&D surveys, technology transfer records.",
    futureExpansion: "Startup registry and incubator program indicators.",
  },
  {
    id: "infrastructure",
    slug: "infrastructure",
    title: "Infrastructure",
    purpose: "Measure infrastructure assets from official infrastructure registries.",
    scope: "Countries and public infrastructure authorities.",
    evidenceExpectations: "Transport, utilities, and connectivity asset datasets.",
    futureExpansion: "Asset condition and maintenance disclosure indicators.",
  },
  {
    id: "environment",
    slug: "environment",
    title: "Environment",
    purpose: "Track environmental conditions from monitoring agencies.",
    scope: "Countries and regulated industries.",
    evidenceExpectations: "Air quality, water quality, land use, emissions inventories.",
    futureExpansion: "Ecosystem and biodiversity monitoring integration.",
  },
  {
    id: "energy",
    slug: "energy",
    title: "Energy",
    purpose: "Document energy production and access from official energy balances.",
    scope: "Countries and energy sector entities.",
    evidenceExpectations: "Energy mix, grid access, renewable capacity statistics.",
    futureExpansion: "Transition pathway indicators with scenario metadata.",
  },
  {
    id: "health",
    slug: "health",
    title: "Health",
    purpose: "Assess health system evidence from WHO and national health statistics.",
    scope: "Countries and health institutions.",
    evidenceExpectations: "Mortality, coverage, facility registry, disease surveillance.",
    futureExpansion: "Health expenditure transparency indicators.",
  },
  {
    id: "employment",
    slug: "employment",
    title: "Employment",
    purpose: "Describe labour market conditions from official labour statistics.",
    scope: "Countries and institutions publishing labour data.",
    evidenceExpectations: "Unemployment, participation, wage statistics from ILO/NSO.",
    futureExpansion: "Sectoral employment and skills mismatch indicators.",
  },
  {
    id: "digital-development",
    slug: "digital-development",
    title: "Digital Development",
    purpose: "Measure digital access and governance from ICT statistics.",
    scope: "Countries and digital infrastructure providers.",
    evidenceExpectations: "Broadband penetration, ICT price baskets, e-government indices.",
    futureExpansion: "Digital public service delivery indicators.",
  },
  {
    id: "public-procurement",
    slug: "public-procurement",
    title: "Public Procurement",
    purpose: "Evaluate procurement transparency from open contracting data.",
    scope: "Countries and public contracting authorities.",
    evidenceExpectations: "Tender notices, award disclosures, OCDS-compliant records.",
    futureExpansion: "Contract performance and red-flag analytics (evidence-bound).",
  },
  {
    id: "budget-transparency",
    slug: "budget-transparency",
    title: "Budget Transparency",
    purpose: "Assess fiscal transparency from published budget documents.",
    scope: "Countries and subnational governments.",
    evidenceExpectations: "Budget proposals, execution reports, audit publications.",
    futureExpansion: "Open spending and beneficiary disclosure indicators.",
  },
  {
    id: "judicial-system",
    slug: "judicial-system",
    title: "Judicial System",
    purpose: "Document judicial system evidence from official legal statistics.",
    scope: "Countries and judicial institutions.",
    evidenceExpectations: "Court structure, case backlog, rule-of-law surveys.",
    futureExpansion: "Case disposition time indicators with court-level provenance.",
  },
  {
    id: "public-services",
    slug: "public-services",
    title: "Public Services",
    purpose: "Measure public service delivery from administrative data.",
    scope: "Countries and service-providing institutions.",
    evidenceExpectations: "Service coverage, wait times, citizen feedback (verified).",
    futureExpansion: "Service quality indicators with audit trails.",
  },
  {
    id: "trade",
    slug: "trade",
    title: "Trade",
    purpose: "Describe trade flows from customs and trade statistics.",
    scope: "Countries and trade-exposed companies.",
    evidenceExpectations: "Import/export volumes, tariff schedules, trade agreements.",
    futureExpansion: "Supply chain disclosure indicators for companies.",
  },
  {
    id: "investment",
    slug: "investment",
    title: "Investment",
    purpose: "Track investment climate evidence from official FDI statistics.",
    scope: "Countries and investors (when registries connect).",
    evidenceExpectations: "FDI inflows, investment promotion agency data, filings.",
    futureExpansion: "Sectoral investment flow indicators.",
  },
  {
    id: "industry",
    slug: "industry",
    title: "Industry",
    purpose: "Classify industrial activity from official industry statistics.",
    scope: "Countries and companies with industry classification.",
    evidenceExpectations: "ISIC/NAICS statistics, production indices, firm registries.",
    futureExpansion: "Industry concentration and productivity indicators.",
  },
  {
    id: "agriculture",
    slug: "agriculture",
    title: "Agriculture",
    purpose: "Document agricultural production from national agricultural statistics.",
    scope: "Countries and agribusiness entities.",
    evidenceExpectations: "Crop yields, land use, FAO statistics, subsidy disclosures.",
    futureExpansion: "Food security and rural development indicators.",
  },
  {
    id: "climate",
    slug: "climate",
    title: "Climate",
    purpose: "Track climate evidence from national communications and inventories.",
    scope: "Countries and regulated emitters.",
    evidenceExpectations: "GHG inventories, NDC submissions, climate finance reports.",
    futureExpansion: "Adaptation implementation tracking indicators.",
  },
  {
    id: "disaster-preparedness",
    slug: "disaster-preparedness",
    title: "Disaster Preparedness",
    purpose: "Assess disaster risk management from official preparedness records.",
    scope: "Countries and emergency management institutions.",
    evidenceExpectations: "Sendai Framework reports, early warning coverage, DRR spending.",
    futureExpansion: "Event response capacity indicators with drill records.",
  },
] as const;

export function getDomainById(
  id: IndicatorDomainDefinition["id"],
): IndicatorDomainDefinition | undefined {
  return INDICATOR_DOMAIN_CATALOG.find((domain) => domain.id === id);
}
