import type { EvidenceSourceRecord } from "@/lib/evidence-infrastructure/types";
import { INFRASTRUCTURE_VERSION } from "@/lib/evidence-infrastructure/types";

function defineSource(
  input: Omit<EvidenceSourceRecord, "infrastructureVersion">,
): EvidenceSourceRecord {
  return { ...input, infrastructureVersion: INFRASTRUCTURE_VERSION };
}

/** Official evidence sources — registered once. No API connections. */
export const OFFICIAL_EVIDENCE_SOURCES: readonly EvidenceSourceRecord[] = [
  defineSource({
    id: "src-un",
    slug: "united-nations",
    name: "United Nations",
    organization: "United Nations",
    officialWebsite: "https://www.un.org",
    coverage: "Global — statistical, treaty, climate, and humanitarian datasets",
    supportedIndicators: [
      "institutional-framework",
      "human-rights-treaty-reporting",
      "trade-flow-disclosure",
      "agriculture-production",
      "emissions-inventory",
      "ndc-submission",
      "sendai-framework-reporting",
      "patent-filing-disclosure",
    ],
    updateFrequency: "Varies by dataset — annual to real-time for some registries",
    license: "UN data terms — per dataset",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-world-bank",
    slug: "world-bank",
    name: "World Bank",
    organization: "World Bank Group",
    officialWebsite: "https://www.worldbank.org",
    coverage: "Global — macroeconomic, development, and infrastructure indicators",
    supportedIndicators: [
      "national-accounts",
      "budget-document-publication",
      "fdi-registration",
      "infrastructure-asset-registry",
      "energy-mix-disclosure",
    ],
    updateFrequency: "Annual and quarterly for WDI; ad hoc for reports",
    license: "World Bank Open Data Terms of Use",
    connectionStatus: "connected",
    verificationStatus: "verified",
  }),
  defineSource({
    id: "src-imf",
    slug: "imf",
    name: "International Monetary Fund",
    organization: "International Monetary Fund",
    officialWebsite: "https://www.imf.org",
    coverage: "Global — fiscal, financial, and balance-of-payments statistics",
    supportedIndicators: ["national-accounts", "fdi-registration"],
    updateFrequency: "Quarterly and annual publications",
    license: "IMF Data Terms and Conditions",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-who",
    slug: "who",
    name: "World Health Organization",
    organization: "World Health Organization",
    officialWebsite: "https://www.who.int",
    coverage: "Global — health statistics and policy references",
    supportedIndicators: ["health-system-coverage"],
    updateFrequency: "Annual Global Health Observatory updates",
    license: "WHO Data Policy",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-unesco",
    slug: "unesco",
    name: "UNESCO",
    organization: "United Nations Educational, Scientific and Cultural Organization",
    officialWebsite: "https://www.unesco.org",
    coverage: "Global — education, science, and culture statistics",
    supportedIndicators: [
      "education-enrollment-statistics",
      "research-output-disclosure",
    ],
    updateFrequency: "Annual UIS releases",
    license: "UNESCO Open Data",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-ilo",
    slug: "ilo",
    name: "International Labour Organization",
    organization: "International Labour Organization",
    officialWebsite: "https://www.ilo.org",
    coverage: "Global — labour market and employment statistics",
    supportedIndicators: ["labour-market-statistics"],
    updateFrequency: "Annual ILOSTAT updates",
    license: "ILO Data License",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-itu",
    slug: "itu",
    name: "International Telecommunication Union",
    organization: "International Telecommunication Union",
    officialWebsite: "https://www.itu.int",
    coverage: "Global — ICT and digital connectivity statistics",
    supportedIndicators: ["digital-connectivity"],
    updateFrequency: "Annual ICT statistics release",
    license: "ITU Terms of Use",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-oecd",
    slug: "oecd",
    name: "OECD",
    organization: "Organisation for Economic Co-operation and Development",
    officialWebsite: "https://www.oecd.org",
    coverage: "OECD member and partner economies — policy and economic data",
    supportedIndicators: [
      "industry-classification",
      "research-output-disclosure",
    ],
    updateFrequency: "Varies by dataset — quarterly to annual",
    license: "OECD Terms and Conditions",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-ocp",
    slug: "open-contracting-partnership",
    name: "Open Contracting Partnership",
    organization: "Open Contracting Partnership",
    officialWebsite: "https://www.open-contracting.org",
    coverage: "Global — procurement transparency standards and OCDS",
    supportedIndicators: ["procurement-disclosure-coverage"],
    updateFrequency: "Continuous registry updates by participating governments",
    license: "OCDS Standard License",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-nso",
    slug: "national-statistics-offices",
    name: "National Statistics Offices",
    organization: "National statistical authorities (per country)",
    officialWebsite: "https://unstats.un.org/home/nso-sites/",
    coverage: "National — official statistics per sovereign state",
    supportedIndicators: [
      "institutional-framework",
      "national-accounts",
      "labour-market-statistics",
      "education-enrollment-statistics",
      "agriculture-production",
      "infrastructure-asset-registry",
      "emissions-inventory",
      "energy-mix-disclosure",
      "health-system-coverage",
      "digital-connectivity",
      "public-service-coverage",
      "judicial-independence-disclosure",
    ],
    updateFrequency: "Per NSO publication calendar",
    license: "National open data terms — per country",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-procurement-portals",
    slug: "official-procurement-portals",
    name: "Official Procurement Portals",
    organization: "Government procurement authorities (per country)",
    officialWebsite: "https://www.open-contracting.org/what-is-open-contracting/ocds/",
    coverage: "National — tender and award disclosure systems",
    supportedIndicators: ["procurement-disclosure-coverage"],
    updateFrequency: "Continuous tender publication cycles",
    license: "Government open data terms — per portal",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-open-budget",
    slug: "national-open-budget-portals",
    name: "National Open Budget Portals",
    organization: "Ministries of finance and audit institutions (per country)",
    officialWebsite: "https://internationalbudget.org/open-budget-survey/",
    coverage: "National — budget documents and execution reports",
    supportedIndicators: ["budget-document-publication"],
    updateFrequency: "Annual budget cycles; mid-year reviews",
    license: "Government publication terms — per country",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-us-census",
    slug: "us-census",
    name: "U.S. Census Bureau",
    organization: "United States Census Bureau",
    officialWebsite: "https://www.census.gov",
    coverage: "United States — demographic and economic statistics (API key required)",
    supportedIndicators: ["national-accounts", "labour-market-statistics"],
    updateFrequency: "Varies by program",
    license: "U.S. Government work",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-us-bea",
    slug: "us-bea",
    name: "U.S. Bureau of Economic Analysis",
    organization: "U.S. Department of Commerce",
    officialWebsite: "https://www.bea.gov",
    coverage: "United States — national accounts (API key required)",
    supportedIndicators: ["national-accounts"],
    updateFrequency: "Quarterly / annual",
    license: "U.S. Government work",
    connectionStatus: "planned",
    verificationStatus: "not_started",
  }),
  defineSource({
    id: "src-us-bls",
    slug: "us-bls",
    name: "U.S. Bureau of Labor Statistics",
    organization: "U.S. Department of Labor",
    officialWebsite: "https://www.bls.gov",
    coverage: "United States — labor market statistics (publicAPI)",
    supportedIndicators: ["labour-market-statistics"],
    updateFrequency: "Monthly",
    license: "U.S. Government work",
    connectionStatus: "connected",
    verificationStatus: "verified",
  }),
  defineSource({
    id: "src-us-sec",
    slug: "us-sec",
    name: "U.S. Securities and Exchange Commission",
    organization: "U.S. SEC",
    officialWebsite: "https://www.sec.gov",
    coverage: "United States — company tickers and filings metadata",
    supportedIndicators: ["industry-classification"],
    updateFrequency: "As published",
    license: "SEC public disclosure",
    connectionStatus: "connected",
    verificationStatus: "verified",
  }),
  defineSource({
    id: "src-cbai-local-registry",
    slug: "cbai-local-registry",
    name: "CBAI Local Platform Registry",
    organization: "CBAI Enterprise",
    officialWebsite: "https://cbai.enterprise",
    coverage: "On-platform entity catalogs — countries, companies, universities",
    supportedIndicators: [
      "industry-classification",
      "education-enrollment-statistics",
      "research-output-disclosure",
    ],
    updateFrequency: "Platform release cycle",
    license: "CBAI Platform Terms",
    connectionStatus: "connected",
    verificationStatus: "verified",
  }),
] as const;

export function getSourceBySlug(slug: string): EvidenceSourceRecord | undefined {
  return OFFICIAL_EVIDENCE_SOURCES.find((s) => s.slug === slug);
}

export function getSourcesByConnectionStatus(
  status: EvidenceSourceRecord["connectionStatus"],
): EvidenceSourceRecord[] {
  return OFFICIAL_EVIDENCE_SOURCES.filter((s) => s.connectionStatus === status);
}

export function getSourcesByVerificationStatus(
  status: EvidenceSourceRecord["verificationStatus"],
): EvidenceSourceRecord[] {
  return OFFICIAL_EVIDENCE_SOURCES.filter(
    (s) => s.verificationStatus === status,
  );
}
