import type { EntityComponentProps } from "@/lib/entity/entity.types";
import { getEntityTypeLabel } from "@/lib/entity/entity.helpers";
import { ENTITY_SCORE_CONFIGS } from "@/lib/entity/entity.types";

type EntityAISummaryProps = EntityComponentProps & {
  confidence?: number;
  agents?: string[];
};

export default function EntityAISummary({
  entity,
  confidence = 94.2,
  agents = ["Research Agent", "Knowledge Agent"],
}: EntityAISummaryProps) {
  return (
    <div className="relative overflow-hidden rounded-xl border border-zinc-800 bg-zinc-950">
      <div
        aria-hidden="true"
        className="pointer-events-none absolute -right-10 -top-10 h-32 w-32 rounded-full bg-violet-500/10 blur-2xl"
      />

      <div className="relative border-b border-zinc-800 px-6 py-4">
        <div className="flex items-center gap-3">
          <span className="relative flex h-3 w-3">
            <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-violet-400 opacity-50" />
            <span className="relative inline-flex h-3 w-3 rounded-full bg-violet-400" />
          </span>
          <div>
            <h3 className="text-sm font-semibold tracking-wide text-zinc-50">
              CBAI Intelligence Summary
            </h3>
            <p className="text-xs text-zinc-500">
              AI-generated {getEntityTypeLabel(entity.type).toLowerCase()}{" "}
              analysis · {entity.name}
            </p>
          </div>
          <span className="ml-auto rounded-full border border-violet-500/20 bg-violet-500/10 px-2.5 py-0.5 font-mono text-[10px] text-violet-400">
            CBAI CORE
          </span>
        </div>
      </div>

      <div className="relative px-6 py-5">
        <p className="text-sm leading-relaxed text-zinc-300">
          {entity.aiSummary}
        </p>

        <div className="mt-5 flex flex-wrap gap-2 border-t border-zinc-800 pt-5">
          {ENTITY_SCORE_CONFIGS.map((config) => (
            <InsightTag
              key={config.key}
              label={config.label}
              value={`${entity.scores[config.key]}/100`}
            />
          ))}
        </div>
      </div>

      <div className="relative border-t border-zinc-800 px-6 py-3">
        <p className="font-mono text-[10px] text-zinc-600">
          Generated by CBAI Core · {agents.join(" + ")} · Confidence:{" "}
          {confidence}%
        </p>
      </div>
    </div>
  );
}

function InsightTag({ label, value }: { label: string; value: string }) {
  return (
    <span className="inline-flex items-center gap-1.5 rounded-full border border-zinc-800 bg-zinc-900/60 px-3 py-1">
      <span className="text-[10px] text-zinc-600">{label}</span>
      <span className="font-mono text-[10px] font-medium text-zinc-400">
        {value}
      </span>
    </span>
  );
}
