import type { OpenResearchQuestion } from "@/lib/research/open-questions/question-types";

/** Category readiness entries — no actual scientific question text. */
export const OPEN_QUESTION_REGISTRY: readonly OpenResearchQuestion[] = [
  {
    questionId: "oq-readiness-global-unknown-mechanism",
    relatedTopicIds: [],
    questionCategory: "Unknown mechanism",
    futureEvidenceSources: ["Peer-reviewed studies", "Datasets", "Experiment records"],
    humanReviewRequired: true,
    status: "not_connected_yet",
  },
  {
    questionId: "oq-readiness-global-replication",
    relatedTopicIds: [],
    questionCategory: "Replication needed",
    futureEvidenceSources: ["Replication studies", "Clinical studies", "Public health reports"],
    humanReviewRequired: true,
    status: "not_connected_yet",
  },
  {
    questionId: "oq-readiness-global-missing-dataset",
    relatedTopicIds: [],
    questionCategory: "Missing dataset",
    futureEvidenceSources: ["Datasets", "Laboratory records", "Official repositories"],
    humanReviewRequired: true,
    status: "not_connected_yet",
  },
  {
    questionId: "oq-readiness-microbiology-mechanisms",
    relatedTopicIds: ["microbiology"],
    questionCategory: "Unknown mechanism",
    futureEvidenceSources: ["Laboratory records", "Datasets", "Peer-reviewed studies"],
    humanReviewRequired: true,
    status: "future_workspace",
  },
  {
    questionId: "oq-readiness-antibiotic-resistance-replication",
    relatedTopicIds: ["antibiotic-resistance"],
    questionCategory: "Replication needed",
    futureEvidenceSources: ["Clinical studies", "Genomic datasets", "Public health reports"],
    humanReviewRequired: true,
    status: "future_workspace",
  },
  {
    questionId: "oq-readiness-antibiotic-resistance-clinical",
    relatedTopicIds: ["antibiotic-resistance"],
    questionCategory: "Clinical validation",
    futureEvidenceSources: ["Clinical studies", "Public health reports"],
    humanReviewRequired: true,
    status: "not_connected_yet",
  },
  {
    questionId: "oq-readiness-crispr-safety",
    relatedTopicIds: ["crispr"],
    questionCategory: "Safety verification",
    futureEvidenceSources: ["Policy guidance", "Methods papers", "Ethics records"],
    humanReviewRequired: true,
    status: "future_workspace",
  },
  {
    questionId: "oq-readiness-crispr-policy",
    relatedTopicIds: ["crispr"],
    questionCategory: "Policy implications",
    futureEvidenceSources: ["Policy guidance", "Peer-reviewed studies"],
    humanReviewRequired: true,
    status: "not_connected_yet",
  },
  {
    questionId: "oq-readiness-plant-disease-field",
    relatedTopicIds: ["plant-disease-resistance"],
    questionCategory: "Field validation",
    futureEvidenceSources: ["Field studies", "Agricultural datasets", "Peer-reviewed studies"],
    humanReviewRequired: true,
    status: "future_workspace",
  },
  {
    questionId: "oq-readiness-plant-disease-method",
    relatedTopicIds: ["plant-disease-resistance"],
    questionCategory: "Method comparison",
    futureEvidenceSources: ["Field studies", "Methods papers", "Datasets"],
    humanReviewRequired: true,
    status: "not_connected_yet",
  },
] as const;
