import type { CapabilityManifest } from "@/lib/human-centered-workspace/contracts";

const evidencePolicy = {
  evidenceRequiredForConclusion: true,
  limitationsMustRemainVisible: true,
  provenanceRequiredForImports: true,
} as const;

/** Domain-neutral operational capabilities. No occupation or industry routing. */
export const OPERATIONAL_REFERENCE_CAPABILITIES: readonly CapabilityManifest[] = [
  {
    capabilityId: "operations.context",
    version: "1.0.0",
    purpose: "Keep the stated outcome, known facts, unknowns, and constraints visible",
    requiredContext: [{ key: "currentOutcome", reason: "Operations require a human-stated outcome" }],
    optionalContext: [{ key: "knownFacts", reason: "Facts improve the operating context" }],
    inputs: [{ schemaId: "operations.context.input", version: 1 }],
    outputs: [{ schemaId: "operations.context", version: 1 }],
    uiBlocks: [{ blockId: "operations.context-panel", version: 1 }],
    actions: ["work.open_object"],
    evidencePolicy,
    permissions: [],
    integrations: [],
    lifecycle: { initialState: "draft", states: ["draft", "confirmed"], terminalStates: ["confirmed"] },
  },
  {
    capabilityId: "workflow.mapping",
    version: "1.0.0",
    purpose: "Map the real sequence, responsibilities, dependencies, and human gates",
    requiredContext: [{ key: "currentOutcome", reason: "The workflow must serve a stated outcome" }],
    optionalContext: [{ key: "team", reason: "Known people can be connected to responsibilities" }],
    inputs: [{ schemaId: "workflow.mapping.input", version: 1 }],
    outputs: [{ schemaId: "workflow.map", version: 1 }],
    uiBlocks: [{ blockId: "workflow.map-panel", version: 1 }],
    actions: ["navigate.workspace"],
    evidencePolicy,
    permissions: [],
    integrations: [],
    lifecycle: { initialState: "draft", states: ["draft", "reviewed"], terminalStates: ["reviewed"] },
  },
  {
    capabilityId: "evidence.review",
    version: "1.0.0",
    purpose: "Inspect source material, provenance, conflicts, and missing evidence",
    requiredContext: [],
    optionalContext: [{ key: "sourceMaterial", reason: "Approved material can be reviewed" }],
    inputs: [{ schemaId: "evidence.reference", version: 1 }],
    outputs: [{ schemaId: "evidence.review", version: 1 }],
    uiBlocks: [{ blockId: "evidence.review-panel", version: 1 }],
    actions: ["navigate.evidence"],
    evidencePolicy,
    permissions: [],
    integrations: [],
    lifecycle: { initialState: "open", states: ["open", "reviewed"], terminalStates: ["reviewed"] },
  },
  {
    capabilityId: "execution.plan",
    version: "1.0.0",
    purpose: "Prepare accountable next actions without executing before human approval",
    requiredContext: [
      { key: "successCriteria", reason: "Execution needs a verifiable result" },
      { key: "decisionOwner", reason: "Consequential work needs a human owner" },
    ],
    optionalContext: [{ key: "constraints", reason: "Plans must respect real constraints" }],
    inputs: [{ schemaId: "execution.plan.input", version: 1 }],
    outputs: [{ schemaId: "execution.plan", version: 1 }],
    uiBlocks: [{ blockId: "execution.plan-panel", version: 1 }],
    actions: ["operational_object.compose"],
    evidencePolicy,
    permissions: [{ permission: "draft:create", reason: "Prepare a reviewable draft" }],
    integrations: [],
    lifecycle: { initialState: "blocked", states: ["blocked", "draft", "approved"], terminalStates: ["approved"] },
  },
  {
    capabilityId: "operations.monitoring",
    version: "1.0.0",
    purpose: "Track outcomes, deviation, evidence updates, and required human intervention",
    requiredContext: [{ key: "successCriteria", reason: "Monitoring needs an explicit target" }],
    optionalContext: [{ key: "dataSources", reason: "Approved sources can supply real signals" }],
    inputs: [{ schemaId: "monitoring.signal", version: 1 }],
    outputs: [{ schemaId: "monitoring.status", version: 1 }],
    uiBlocks: [{ blockId: "operations.monitoring-panel", version: 1 }],
    actions: ["navigate.workspace"],
    evidencePolicy,
    permissions: [],
    integrations: [],
    lifecycle: { initialState: "blocked", states: ["blocked", "active", "paused"], terminalStates: [] },
  },
];

