export {
  RESEARCH_HOME,
  RESEARCH_HOME_VERSION,
  RESEARCH_EXAMPLE_TOPICS,
  RESEARCH_WORKSPACE_AREAS,
  RESEARCH_PRINCIPLES,
  RESEARCH_AVAILABLE_TODAY,
  RESEARCH_NOT_AVAILABLE_YET,
  RESEARCH_UNIVERSITIES_LINK,
  type ResearchPrinciple,
  type ResearchWorkspaceArea,
} from "@/lib/research/research-home";
