export {
  RESEARCH_HOME,
  RESEARCH_HOME_VERSION,
  RESEARCH_EXAMPLE_TOPICS,
  RESEARCH_WORKSPACE_AREAS,
  RESEARCH_PRINCIPLES,
  RESEARCH_AVAILABLE_TODAY,
  RESEARCH_NOT_AVAILABLE_YET,
  RESEARCH_UNIVERSITIES_LINK,
  type ResearchPrinciple,
  type ResearchWorkspaceArea,
} from "@/lib/research/research-home";

export {
  RESEARCH_DOMAINS,
  RESEARCH_TOPICS,
  RESEARCH_TOPIC_STATUS_LABELS,
  RESEARCH_TOPIC_AVAILABLE_TODAY,
  RESEARCH_TOPIC_NOT_AVAILABLE_YET,
  RESEARCH_TOPIC_FUTURE_SUPPORTS,
  filterResearchTopics,
  getResearchTopicCountByDomain,
  getResearchTopicById,
  getResearchTopicPath,
  type ResearchDomain,
  type ResearchDomainId,
  type ResearchTopic,
  type ResearchTopicStatus,
} from "@/lib/research/research-topics";

export {
  RESEARCH_ENTITY_TYPES,
  RESEARCH_ENTITY_TYPE_DEFINITIONS,
  RESEARCH_ENTITY_EVIDENCE_STATUS_LABELS,
  RESEARCH_ENTITY_SOURCE_STATUS_LABELS,
  RESEARCH_ENTITY_WORKSPACE_STATUS_LABELS,
  RESEARCH_ENTITY_MODEL_VERSION,
  RESEARCH_ENTITY_REGISTRY,
  findResearchEntityById,
  findResearchEntitiesByType,
  findResearchEntitiesByTopic,
  listResearchEntityTypes,
  listSeededResearchEntityTypes,
  resolveResearchEntityRelations,
  validateResearchEntityRegistry,
  type ResearchEntity,
  type ResearchEntityType,
  type ResearchEntityTypeDefinition,
  type ResearchEntityEvidenceStatus,
  type ResearchEntitySourceStatus,
  type ResearchEntityWorkspaceStatus,
  type ResearchEntityRelation,
  type ResearchEntityValidationIssue,
  type ResearchEntityValidationReport,
} from "@/lib/research/entities";

export {
  PUBLICATION_FUTURE_SOURCE_TYPES,
  PUBLICATION_EXPECTED_METADATA_FIELDS,
  PUBLICATION_LAYER_SOURCE_STATUS_LABELS,
  PUBLICATION_LAYER_EVIDENCE_STATUS_LABELS,
  PUBLICATION_EXPECTED_METADATA_LABELS,
  PUBLICATION_LAYER_VERSION,
  PUBLICATION_LAYER_GLOBAL_LIMITATIONS,
  PUBLICATION_LAYER_FUTURE_CAPABILITIES,
  PUBLICATION_TOPIC_NOT_CONNECTED_MESSAGE,
  PUBLICATION_LAYER_REGISTRY,
  findPublicationLayerById,
  findPublicationLayerByTopic,
  listPublicationSourceTypes,
  listExpectedMetadataFields,
  getPublicationReadinessForTopic,
  listPublicationLayers,
  getDefaultPublicationLimitations,
  getDefaultPublicationFutureCapabilities,
  validatePublicationLayerRegistry,
  isValidPublicationLayerSourceStatus,
  isValidPublicationLayerEvidenceStatus,
  type PublicationFutureSourceType,
  type PublicationExpectedMetadataField,
  type PublicationLayerSourceStatus,
  type PublicationLayerEvidenceStatus,
  type PublicationLayer,
  type PublicationTopicReadiness,
  type PublicationLayerValidationIssue,
  type PublicationLayerValidationReport,
} from "@/lib/research/publications";

export {
  EXPERIMENT_FUTURE_TYPES,
  EXPERIMENT_EXPECTED_METADATA_FIELDS,
  EXPERIMENT_LAYER_SOURCE_STATUS_LABELS,
  EXPERIMENT_LAYER_EVIDENCE_STATUS_LABELS,
  EXPERIMENT_EXPECTED_METADATA_LABELS,
  EXPERIMENT_LAYER_VERSION,
  EXPERIMENT_LAYER_GLOBAL_LIMITATIONS,
  EXPERIMENT_LAYER_FUTURE_CAPABILITIES,
  EXPERIMENT_TOPIC_NOT_CONNECTED_MESSAGE,
  EXPERIMENT_LAYER_REGISTRY,
  findExperimentLayerById,
  findExperimentLayerByTopic,
  listExperimentTypes,
  listExpectedExperimentMetadataFields,
  getExperimentReadinessForTopic,
  listExperimentLayers,
  getDefaultExperimentLimitations,
  getDefaultExperimentFutureCapabilities,
  validateExperimentLayerRegistry,
  isValidExperimentLayerSourceStatus,
  isValidExperimentLayerEvidenceStatus,
  type ExperimentFutureType,
  type ExperimentExpectedMetadataField,
  type ExperimentLayerSourceStatus,
  type ExperimentLayerEvidenceStatus,
  type ExperimentLayer,
  type ExperimentTopicReadiness,
  type ExperimentLayerValidationIssue,
  type ExperimentLayerValidationReport,
} from "@/lib/research/experiments";

export {
  LABORATORY_FUTURE_TYPES,
  LABORATORY_EXPECTED_METADATA_FIELDS,
  LABORATORY_LAYER_SOURCE_STATUS_LABELS,
  LABORATORY_LAYER_EVIDENCE_STATUS_LABELS,
  LABORATORY_EXPECTED_METADATA_LABELS,
  LABORATORY_LAYER_VERSION,
  LABORATORY_LAYER_GLOBAL_LIMITATIONS,
  LABORATORY_LAYER_FUTURE_CAPABILITIES,
  LABORATORY_TOPIC_NOT_CONNECTED_MESSAGE,
  LABORATORY_LAYER_REGISTRY,
  findLaboratoryLayerById,
  findLaboratoryLayerByTopic,
  listLaboratoryTypes,
  listExpectedLaboratoryMetadataFields,
  getLaboratoryReadinessForTopic,
  listLaboratoryLayers,
  getDefaultLaboratoryLimitations,
  getDefaultLaboratoryFutureCapabilities,
  validateLaboratoryLayerRegistry,
  isValidLaboratoryLayerSourceStatus,
  isValidLaboratoryLayerEvidenceStatus,
  type LaboratoryFutureType,
  type LaboratoryExpectedMetadataField,
  type LaboratoryLayerSourceStatus,
  type LaboratoryLayerEvidenceStatus,
  type LaboratoryLayer,
  type LaboratoryTopicReadiness,
  type LaboratoryLayerValidationIssue,
  type LaboratoryLayerValidationReport,
} from "@/lib/research/laboratories";

export {
  RESEARCHER_FUTURE_TYPES,
  RESEARCHER_EXPECTED_PROFILE_METADATA,
  RESEARCHER_VERIFICATION_SOURCES,
  RESEARCHER_LAYER_SOURCE_STATUS_LABELS,
  RESEARCHER_LAYER_EVIDENCE_STATUS_LABELS,
  RESEARCHER_EXPECTED_PROFILE_METADATA_LABELS,
  RESEARCHER_LAYER_VERSION,
  RESEARCHER_LAYER_GLOBAL_LIMITATIONS,
  RESEARCHER_LAYER_FUTURE_CAPABILITIES,
  RESEARCHER_TOPIC_NOT_CONNECTED_MESSAGE,
  RESEARCHER_LAYER_REGISTRY,
  findResearcherLayerById,
  findResearcherLayerByTopic,
  listResearcherTypes,
  listExpectedProfileMetadataFields,
  listVerificationSources,
  getResearcherReadinessForTopic,
  listResearcherLayers,
  getDefaultResearcherLimitations,
  getDefaultResearcherFutureCapabilities,
  validateResearcherLayerRegistry,
  isValidResearcherLayerSourceStatus,
  isValidResearcherLayerEvidenceStatus,
  type ResearcherFutureType,
  type ResearcherExpectedProfileMetadata,
  type ResearcherVerificationSource,
  type ResearcherLayerSourceStatus,
  type ResearcherLayerEvidenceStatus,
  type ResearcherLayer,
  type ResearcherTopicReadiness,
  type ResearcherLayerValidationIssue,
  type ResearcherLayerValidationReport,
} from "@/lib/research/researchers";

export {
  OPEN_QUESTION_CATEGORIES,
  OPEN_QUESTION_STATUS_LABELS,
  OPEN_QUESTION_CATEGORY_DESCRIPTIONS,
  OPEN_QUESTION_MODEL_VERSION,
  OPEN_QUESTIONS_NOT_CONNECTED_MESSAGE,
  type OpenQuestionCategory,
  type OpenQuestionStatus,
  type OpenResearchQuestion,
} from "@/lib/research/open-questions/question-types";

export { OPEN_QUESTION_REGISTRY } from "@/lib/research/open-questions/question-registry";

export {
  findOpenQuestionById,
  findOpenQuestionsByTopic,
  listOpenQuestionCategories,
  getOpenQuestionsForTopic,
  listOpenQuestions,
  type OpenQuestionTopicContext,
} from "@/lib/research/open-questions/question-query";

export {
  NEGATIVE_RESULT_STATUS_LABELS,
  NEGATIVE_RESULT_PRESERVATION_PURPOSE,
  NEGATIVE_RESULT_MODEL_VERSION,
  NEGATIVE_RESULTS_NOT_CONNECTED_MESSAGE,
  type NegativeResultStatus,
  type NegativeResultReadiness,
} from "@/lib/research/negative-results/negative-result-types";

export { NEGATIVE_RESULT_REGISTRY } from "@/lib/research/negative-results/negative-result-registry";

export {
  findNegativeResultById,
  findNegativeResultsByTopic,
  getNegativeResultsForTopic,
  listNegativeResults,
  type NegativeResultTopicContext,
} from "@/lib/research/negative-results/negative-result-query";

export {
  RESEARCH_GRAPH_NODE_TYPES,
  RESEARCH_GRAPH_RELATIONSHIP_TYPES,
  RESEARCH_GRAPH_STATUS_LABELS,
  RESEARCH_GRAPH_NODE_TYPE_LABELS,
  RESEARCH_GRAPH_RELATIONSHIP_LABELS,
  RESEARCH_GRAPH_HONEST_NOTICE,
  RESEARCH_GRAPH_RELATED_TOPIC_LABEL,
  RESEARCH_GRAPH_VERSION,
  buildResearchGraphForTopic,
  buildGlobalResearchGraphPreview,
  buildDomainResearchGraph,
  findRelatedTopicsByCatalog,
  getResearchGraphForTopic,
  getResearchGraphForTopicObject,
  getGlobalResearchGraphPreview,
  getRelatedTopicsForGraph,
  findGraphNode,
  groupGraphNodesByType,
  getEdgesFromNode,
  validateResearchGraph,
  type ResearchGraphNodeType,
  type ResearchGraphRelationshipType,
  type ResearchGraphStatus,
  type ResearchGraphNode,
  type ResearchGraphEdge,
  type ResearchGraph,
  type ResearchGraphValidationIssue,
  type ResearchGraphValidationReport,
} from "@/lib/research/graph";

export {
  NOTEBOOK_SUMMARY_SECTION_IDS,
  NOTEBOOK_STATUS_LABELS,
  NOTEBOOK_VERSION,
  NOTEBOOK_CATALOG_ONLY_NOTICE,
  NOTEBOOK_HUMAN_REVIEW_NOTICE,
  NOTEBOOK_SUMMARY_SECTION_TITLES,
  buildResearchNotebook,
  getResearchNotebookForTopic,
  getResearchNotebookForTopicObject,
  findNotebookSummarySection,
  validateResearchNotebook,
  isValidNotebookStatus,
  type NotebookSummarySectionId,
  type NotebookStatus,
  type NotebookSummarySection,
  type NotebookGraphConnection,
  type ResearchNotebook,
  type ResearchNotebookValidationIssue,
  type ResearchNotebookValidationReport,
} from "@/lib/research/notebook";

export {
  TIMELINE_STAGE_IDS,
  TIMELINE_STAGE_STATUS_LABELS,
  TIMELINE_STAGE_DEFINITIONS,
  TIMELINE_VERSION,
  TIMELINE_WORKFLOW_NOTICE,
  TIMELINE_HUMAN_REVIEW_NOTICE,
  buildKnowledgeTimeline,
  getRequiredTimelineStageIds,
  getKnowledgeTimelineForTopic,
  getKnowledgeTimelineForTopicObject,
  findTimelineStage,
  validateKnowledgeTimeline,
  isValidTimelineStageStatus,
  type TimelineStageId,
  type TimelineStageStatus,
  type TimelineOverallStatus,
  type KnowledgeTimelineStage,
  type KnowledgeTimeline,
  type KnowledgeTimelineValidationIssue,
  type KnowledgeTimelineValidationReport,
} from "@/lib/research/timeline";

export {
  WORKSPACE_SUPPORTED_OBJECTS,
  WORKSPACE_MODULES,
  WORKSPACE_LIFECYCLE_STAGES,
  WORKSPACE_STATUS_LABELS,
  WORKSPACE_VERSION,
  WORKSPACE_AVAILABLE_TODAY,
  WORKSPACE_NOT_AVAILABLE_YET,
  WORKSPACE_SHELL_NOTICE,
  WORKSPACE_HUMAN_REVIEW_NOTICE,
  WORKSPACE_PATH,
  RESEARCH_WORKSPACE,
  WORKSPACE_OVERVIEW_COPY,
  getResearchWorkspace,
  isWorkspaceModuleActive,
  type WorkspaceSupportedObject,
  type WorkspaceModule,
  type WorkspaceLifecycleStageId,
  type WorkspaceStatus,
  type ResearchWorkspaceModel,
} from "@/lib/research/workspace";

export {
  DISCOVERY_RELATIONSHIP_REASONS,
  DISCOVERY_MODEL_VERSION,
  DISCOVERY_RELATIONSHIP_REASON_LABELS,
  DISCOVERY_STATUS_LABELS,
  DISCOVERY_CATALOG_NOTICE,
  DISCOVERY_HUMAN_REVIEW_NOTICE,
  buildCrossTopicDiscovery,
  buildCrossTopicDiscoveriesForTopic,
  getCrossTopicDiscoveriesForTopic,
  getCrossTopicDiscoveryContext,
  findCrossTopicDiscovery,
  validateCrossTopicDiscoveries,
  type DiscoveryRelationshipReason,
  type DiscoveryStatus,
  type CrossTopicDiscovery,
  type CrossTopicDiscoveryContext,
  type DiscoveryValidationIssue,
  type DiscoveryValidationReport,
} from "@/lib/research/discovery";

export {
  RESEARCH_GAP_TYPES,
  RESEARCH_GAP_MODEL_VERSION,
  RESEARCH_GAP_TYPE_LABELS,
  RESEARCH_GAP_STATUS_LABELS,
  RESEARCH_GAP_HONEST_NOTICE,
  RESEARCH_GAP_HUMAN_REVIEW_NOTICE,
  WORKSPACE_GAP_TYPES,
  TOPIC_GAP_PRIORITY,
  buildResearchGapsForTopic,
  buildResearchGapContext,
  selectTopicDetailGaps,
  listTopicMissingAreas,
  getResearchGapContextForTopic,
  getResearchGapContext,
  getResearchGapsForTopic,
  getResearchGapsByType,
  getTopicDetailResearchGaps,
  getWorkspaceResearchGaps,
  findResearchGapByType,
  validateResearchGaps,
  type ResearchGapType,
  type ResearchGapStatus,
  type ResearchGap,
  type ResearchGapSummaryData,
  type ResearchGapContext,
  type ResearchGapValidationIssue,
  type ResearchGapValidationReport,
} from "@/lib/research/gaps";

export {
  METHOD_COMPARISON_STATUSES,
  METHOD_COMPARISON_MODEL_VERSION,
  METHOD_COMPARISON_STATUS_LABELS,
  METHOD_COMPARISON_HONEST_NOTICE,
  METHOD_COMPARISON_HUMAN_REVIEW_NOTICE,
  METHOD_COMPARISON_LIMITATIONS,
  WORKSPACE_METHOD_PREVIEW_LIMIT,
  WORKSPACE_METHOD_PREVIEW_MIN,
  buildMethodComparisonForTopic,
  buildMethodEvidenceMatrix,
  selectWorkspaceMethodRows,
  getMethodComparisonForTopic,
  getMethodComparison,
  getMethodEvidenceMatrixForTopic,
  getWorkspaceMethodRows,
  validateMethodComparison,
  validateMethodComparisons,
  type MethodComparisonStatus,
  type MethodEvidenceRow,
  type MethodEvidenceMatrixCell,
  type MethodComparison,
  type MethodComparisonValidationIssue,
  type MethodComparisonValidationReport,
} from "@/lib/research/method-comparison";
