export type ResearchTopicStatus =
  | "catalog_available"
  | "workspace_not_available"
  | "evidence_not_connected";

export type ResearchDomainId =
  | "life-sciences"
  | "medicine"
  | "agriculture"
  | "climate-environment"
  | "energy"
  | "materials-science"
  | "engineering"
  | "computer-science"
  | "economics-policy"
  | "social-sciences";

export type ResearchDomain = {
  domainId: ResearchDomainId;
  domainName: string;
};

export type ResearchTopic = {
  topicId: string;
  topicName: string;
  domain: string;
  domainId: ResearchDomainId;
  description: string;
  relatedMethods: readonly string[];
  relatedEvidenceTypes: readonly string[];
  status: ResearchTopicStatus;
  futureWorkspace: string;
};

export const RESEARCH_TOPIC_STATUS_LABELS: Record<ResearchTopicStatus, string> = {
  catalog_available: "Catalog available",
  workspace_not_available: "Workspace not available",
  evidence_not_connected: "Evidence not connected",
};

export const RESEARCH_TOPIC_AVAILABLE_TODAY = [
  "Catalog profile for this research topic",
  "Domain classification",
  "Related methods listed in the catalog",
  "Related evidence types listed in the catalog",
] as const;

export const RESEARCH_TOPIC_NOT_AVAILABLE_YET = [
  "Live publications not connected",
  "Researchers not connected",
  "Experiments not connected",
  "Datasets not connected",
  "Patents not connected",
  "Evidence discussions not connected",
  "AI Notebook not connected",
] as const;

export const RESEARCH_TOPIC_FUTURE_SUPPORTS = [
  "Publications",
  "Experiments",
  "Datasets",
  "Patents",
  "Laboratories",
  "Open questions",
  "Evidence discussions",
  "AI Notebook",
] as const;

export const RESEARCH_DOMAINS: readonly ResearchDomain[] = [
  { domainId: "life-sciences", domainName: "Life Sciences" },
  { domainId: "medicine", domainName: "Medicine" },
  { domainId: "agriculture", domainName: "Agriculture" },
  { domainId: "climate-environment", domainName: "Climate & Environment" },
  { domainId: "energy", domainName: "Energy" },
  { domainId: "materials-science", domainName: "Materials Science" },
  { domainId: "engineering", domainName: "Engineering" },
  { domainId: "computer-science", domainName: "Computer Science" },
  { domainId: "economics-policy", domainName: "Economics & Policy" },
  { domainId: "social-sciences", domainName: "Social Sciences" },
] as const;

export const RESEARCH_TOPICS: readonly ResearchTopic[] = [
  // Life Sciences
  {
    topicId: "microbiology",
    topicName: "Microbiology",
    domain: "Life Sciences",
    domainId: "life-sciences",
    description: "Study of microorganisms, cultures, and microbial systems relevant to health and environment.",
    relatedMethods: ["Culture methods", "Sequencing", "Microscopy"],
    relatedEvidenceTypes: ["Laboratory records", "Peer-reviewed studies", "Datasets"],
    status: "catalog_available",
    futureWorkspace: "Microbiology topic page with methods, sources, and open questions.",
  },
  {
    topicId: "antibiotic-resistance",
    topicName: "Antibiotic resistance",
    domain: "Life Sciences",
    domainId: "life-sciences",
    description: "Research on resistance mechanisms, surveillance, and stewardship across microbial populations.",
    relatedMethods: ["Surveillance studies", "Genomic analysis", "Clinical correlation"],
    relatedEvidenceTypes: ["Public health reports", "Genomic datasets", "Clinical studies"],
    status: "evidence_not_connected",
    futureWorkspace: "Resistance mapping workspace with source status and open questions.",
  },
  {
    topicId: "crispr",
    topicName: "CRISPR",
    domain: "Life Sciences",
    domainId: "life-sciences",
    description: "Gene editing methods, applications, and governance questions in biological research.",
    relatedMethods: ["Gene editing protocols", "Off-target analysis", "Ethics review"],
    relatedEvidenceTypes: ["Methods papers", "Patents", "Policy guidance"],
    status: "workspace_not_available",
    futureWorkspace: "CRISPR methods and evidence review workspace.",
  },
  {
    topicId: "genomics",
    topicName: "Genomics",
    domain: "Life Sciences",
    domainId: "life-sciences",
    description: "Genome structure, variation, and interpretation across organisms and populations.",
    relatedMethods: ["Whole-genome sequencing", "Variant calling", "Comparative genomics"],
    relatedEvidenceTypes: ["Sequence datasets", "Reference genomes", "Methods documentation"],
    status: "catalog_available",
    futureWorkspace: "Genomics topic page with dataset and methods references.",
  },
  {
    topicId: "virology",
    topicName: "Virology",
    domain: "Life Sciences",
    domainId: "life-sciences",
    description: "Virus biology, transmission research, and diagnostic method development.",
    relatedMethods: ["Serological assays", "Molecular detection", "Epidemiological modeling"],
    relatedEvidenceTypes: ["Surveillance data", "Laboratory methods", "Clinical reports"],
    status: "evidence_not_connected",
    futureWorkspace: "Virology evidence workspace with source connection status.",
  },
  {
    topicId: "synthetic-biology",
    topicName: "Synthetic biology",
    domain: "Life Sciences",
    domainId: "life-sciences",
    description: "Engineered biological systems, biosafety, and reproducibility in designed organisms.",
    relatedMethods: ["Design-build-test cycles", "Biosafety review", "Standard parts libraries"],
    relatedEvidenceTypes: ["Protocols", "Regulatory filings", "Open methods"],
    status: "workspace_not_available",
    futureWorkspace: "Synthetic biology methods and safety review workspace.",
  },
  {
    topicId: "biodiversity-mapping",
    topicName: "Biodiversity mapping",
    domain: "Life Sciences",
    domainId: "life-sciences",
    description: "Species distribution, taxonomy updates, and ecological survey methods.",
    relatedMethods: ["Field surveys", "eDNA sampling", "Taxonomic classification"],
    relatedEvidenceTypes: ["Survey datasets", "Species registries", "Observational records"],
    status: "catalog_available",
    futureWorkspace: "Biodiversity topic page linked to geographic and species evidence.",
  },
  // Medicine
  {
    topicId: "cancer-research",
    topicName: "Cancer research",
    domain: "Medicine",
    domainId: "medicine",
    description: "Oncology research topics spanning diagnosis, treatment methods, and population studies.",
    relatedMethods: ["Clinical trials", "Biomarker analysis", "Survival analysis"],
    relatedEvidenceTypes: ["Clinical studies", "Registry data", "Treatment protocols"],
    status: "evidence_not_connected",
    futureWorkspace: "Cancer research topic page with trial and publication evidence types.",
  },
  {
    topicId: "vaccine-development",
    topicName: "Vaccine development",
    domain: "Medicine",
    domainId: "medicine",
    description: "Immunization research, trial phases, and post-market surveillance methods.",
    relatedMethods: ["Randomized trials", "Immunogenicity assays", "Pharmacovigilance"],
    relatedEvidenceTypes: ["Trial registrations", "Regulatory summaries", "Safety reports"],
    status: "workspace_not_available",
    futureWorkspace: "Vaccine development evidence and methods workspace.",
  },
  {
    topicId: "public-health-systems",
    topicName: "Public health systems",
    domain: "Medicine",
    domainId: "medicine",
    description: "Health system capacity, delivery models, and population health measurement.",
    relatedMethods: ["Health surveys", "Outcome tracking", "Policy evaluation"],
    relatedEvidenceTypes: ["Official health statistics", "Survey data", "Policy documents"],
    status: "catalog_available",
    futureWorkspace: "Public health systems topic page with official source status.",
  },
  {
    topicId: "clinical-trial-methods",
    topicName: "Clinical trial methods",
    domain: "Medicine",
    domainId: "medicine",
    description: "Trial design, registration, reporting standards, and reproducibility requirements.",
    relatedMethods: ["Preregistration", "Blinding protocols", "Statistical analysis plans"],
    relatedEvidenceTypes: ["Trial registries", "Protocols", "Results reporting"],
    status: "catalog_available",
    futureWorkspace: "Clinical methods topic page with standards and open questions.",
  },
  {
    topicId: "rare-disease-research",
    topicName: "Rare disease research",
    domain: "Medicine",
    domainId: "medicine",
    description: "Orphan conditions, patient registries, and evidence gaps in small populations.",
    relatedMethods: ["Patient registries", "Case series analysis", "Natural history studies"],
    relatedEvidenceTypes: ["Registry records", "Case reports", "Genetic findings"],
    status: "evidence_not_connected",
    futureWorkspace: "Rare disease topic workspace with registry source status.",
  },
  {
    topicId: "medical-imaging",
    topicName: "Medical imaging",
    domain: "Medicine",
    domainId: "medicine",
    description: "Imaging modalities, validation methods, and diagnostic evidence standards.",
    relatedMethods: ["Imaging validation", "Reader studies", "AI-assisted review"],
    relatedEvidenceTypes: ["Imaging protocols", "Validation studies", "Diagnostic accuracy data"],
    status: "workspace_not_available",
    futureWorkspace: "Medical imaging methods and evidence review page.",
  },
  {
    topicId: "mental-health-research",
    topicName: "Mental health research",
    domain: "Medicine",
    domainId: "medicine",
    description: "Psychological and psychiatric research methods, outcomes, and service evaluation.",
    relatedMethods: ["Standardized assessments", "Longitudinal cohorts", "Intervention trials"],
    relatedEvidenceTypes: ["Clinical assessments", "Survey instruments", "Trial outcomes"],
    status: "catalog_available",
    futureWorkspace: "Mental health topic page with methods and source transparency.",
  },
  // Agriculture
  {
    topicId: "food-security",
    topicName: "Food security",
    domain: "Agriculture",
    domainId: "agriculture",
    description: "Supply stability, nutrition access, and agricultural resilience research.",
    relatedMethods: ["Yield modeling", "Nutrition surveys", "Supply chain mapping"],
    relatedEvidenceTypes: ["Agricultural statistics", "Nutrition data", "Trade records"],
    status: "catalog_available",
    futureWorkspace: "Food security topic page with official agricultural evidence.",
  },
  {
    topicId: "plant-disease-resistance",
    topicName: "Plant disease resistance",
    domain: "Agriculture",
    domainId: "agriculture",
    description: "Crop protection, breeding methods, and pathogen surveillance in agriculture.",
    relatedMethods: ["Field trials", "Resistance screening", "Pathogen genotyping"],
    relatedEvidenceTypes: ["Trial data", "Breeding records", "Surveillance reports"],
    status: "workspace_not_available",
    futureWorkspace: "Plant disease resistance methods and evidence workspace.",
  },
  {
    topicId: "soil-health",
    topicName: "Soil health",
    domain: "Agriculture",
    domainId: "agriculture",
    description: "Soil composition, fertility management, and sustainable farming practices.",
    relatedMethods: ["Soil sampling", "Nutrient analysis", "Long-term plot studies"],
    relatedEvidenceTypes: ["Soil surveys", "Agronomic trials", "Environmental monitoring"],
    status: "catalog_available",
    futureWorkspace: "Soil health topic page with methods and dataset references.",
  },
  {
    topicId: "crop-genetics",
    topicName: "Crop genetics",
    domain: "Agriculture",
    domainId: "agriculture",
    description: "Genetic improvement, trait mapping, and seed system transparency.",
    relatedMethods: ["Marker-assisted breeding", "GWAS", "Field performance trials"],
    relatedEvidenceTypes: ["Genetic datasets", "Variety registries", "Trial results"],
    status: "evidence_not_connected",
    futureWorkspace: "Crop genetics topic workspace with connected source status.",
  },
  {
    topicId: "sustainable-irrigation",
    topicName: "Sustainable irrigation",
    domain: "Agriculture",
    domainId: "agriculture",
    description: "Water use efficiency, irrigation technology, and drought adaptation in farming.",
    relatedMethods: ["Water balance modeling", "Sensor monitoring", "Pilot evaluations"],
    relatedEvidenceTypes: ["Water use data", "Pilot reports", "Engineering specifications"],
    status: "catalog_available",
    futureWorkspace: "Sustainable irrigation topic page with methods and open questions.",
  },
  {
    topicId: "agricultural-policy-review",
    topicName: "Agricultural policy review",
    domain: "Agriculture",
    domainId: "agriculture",
    description: "Policy analysis for subsidies, trade rules, and rural development programs.",
    relatedMethods: ["Policy document review", "Impact evaluation", "Stakeholder analysis"],
    relatedEvidenceTypes: ["Official policy texts", "Evaluation reports", "Statistical yearbooks"],
    status: "workspace_not_available",
    futureWorkspace: "Agricultural policy evidence review workspace.",
  },
  // Climate & Environment
  {
    topicId: "climate-adaptation",
    topicName: "Climate adaptation",
    domain: "Climate & Environment",
    domainId: "climate-environment",
    description: "Adaptation planning, vulnerability assessment, and resilience research methods.",
    relatedMethods: ["Scenario analysis", "Vulnerability mapping", "Cost-benefit review"],
    relatedEvidenceTypes: ["Climate projections", "Adaptation plans", "Impact assessments"],
    status: "catalog_available",
    futureWorkspace: "Climate adaptation topic page with official climate evidence types.",
  },
  {
    topicId: "water-purification",
    topicName: "Water purification",
    domain: "Climate & Environment",
    domainId: "climate-environment",
    description: "Treatment methods, quality monitoring, and access research for safe water.",
    relatedMethods: ["Water quality testing", "Treatment pilot studies", "Monitoring networks"],
    relatedEvidenceTypes: ["Quality measurements", "Treatment standards", "Infrastructure reports"],
    status: "catalog_available",
    futureWorkspace: "Water purification topic page with methods and source status.",
  },
  {
    topicId: "carbon-cycle-research",
    topicName: "Carbon cycle research",
    domain: "Climate & Environment",
    domainId: "climate-environment",
    description: "Carbon sources, sinks, and measurement methods in earth systems.",
    relatedMethods: ["Flux measurements", "Inventory methods", "Satellite validation"],
    relatedEvidenceTypes: ["Emissions inventories", "Sensor datasets", "Model outputs"],
    status: "evidence_not_connected",
    futureWorkspace: "Carbon cycle evidence workspace with dataset connection status.",
  },
  {
    topicId: "ocean-ecology",
    topicName: "Ocean ecology",
    domain: "Climate & Environment",
    domainId: "climate-environment",
    description: "Marine ecosystems, fisheries research, and ocean monitoring methods.",
    relatedMethods: ["Marine surveys", "Acoustic monitoring", "Ecosystem modeling"],
    relatedEvidenceTypes: ["Oceanographic data", "Fishery statistics", "Survey reports"],
    status: "workspace_not_available",
    futureWorkspace: "Ocean ecology topic page with marine evidence types.",
  },
  {
    topicId: "air-quality-monitoring",
    topicName: "Air quality monitoring",
    domain: "Climate & Environment",
    domainId: "climate-environment",
    description: "Pollutant measurement, exposure research, and regulatory compliance methods.",
    relatedMethods: ["Sensor networks", "Exposure modeling", "Standards comparison"],
    relatedEvidenceTypes: ["Monitoring data", "Regulatory limits", "Health impact studies"],
    status: "catalog_available",
    futureWorkspace: "Air quality topic page with official monitoring source status.",
  },
  {
    topicId: "biodiversity-conservation",
    topicName: "Biodiversity conservation",
    domain: "Climate & Environment",
    domainId: "climate-environment",
    description: "Protected areas, species recovery, and conservation policy evaluation.",
    relatedMethods: ["Habitat assessment", "Population monitoring", "Policy review"],
    relatedEvidenceTypes: ["Conservation plans", "Species status lists", "Protected area records"],
    status: "catalog_available",
    futureWorkspace: "Biodiversity conservation topic workspace.",
  },
  {
    topicId: "environmental-impact-assessment",
    topicName: "Environmental impact assessment",
    domain: "Climate & Environment",
    domainId: "climate-environment",
    description: "EIA methods, baseline studies, and mitigation monitoring for projects.",
    relatedMethods: ["Baseline surveys", "Impact modeling", "Mitigation tracking"],
    relatedEvidenceTypes: ["EIA reports", "Baseline datasets", "Monitoring plans"],
    status: "workspace_not_available",
    futureWorkspace: "Environmental impact assessment evidence review page.",
  },
  // Energy
  {
    topicId: "quantum-battery",
    topicName: "Quantum battery",
    domain: "Energy",
    domainId: "energy",
    description: "Quantum-enabled storage concepts, materials research, and feasibility methods.",
    relatedMethods: ["Materials characterization", "Theoretical modeling", "Lab prototypes"],
    relatedEvidenceTypes: ["Research papers", "Patents", "Lab notebooks"],
    status: "workspace_not_available",
    futureWorkspace: "Quantum battery topic page with methods and open questions.",
  },
  {
    topicId: "clean-energy-storage",
    topicName: "Clean energy storage",
    domain: "Energy",
    domainId: "energy",
    description: "Battery, thermal, and mechanical storage research for renewable integration.",
    relatedMethods: ["Cycle testing", "Grid simulation", "Lifecycle assessment"],
    relatedEvidenceTypes: ["Performance data", "Grid studies", "Standards documents"],
    status: "catalog_available",
    futureWorkspace: "Clean energy storage topic workspace.",
  },
  {
    topicId: "solar-cell-materials",
    topicName: "Solar cell materials",
    domain: "Energy",
    domainId: "energy",
    description: "Photovoltaic materials, efficiency research, and durability testing.",
    relatedMethods: ["Efficiency testing", "Degradation studies", "Materials synthesis"],
    relatedEvidenceTypes: ["Lab measurements", "Durability reports", "Patents"],
    status: "catalog_available",
    futureWorkspace: "Solar materials topic page with evidence type references.",
  },
  {
    topicId: "grid-reliability",
    topicName: "Grid reliability",
    domain: "Energy",
    domainId: "energy",
    description: "Power system stability, outage analysis, and infrastructure resilience.",
    relatedMethods: ["Reliability modeling", "Outage analysis", "Stress testing"],
    relatedEvidenceTypes: ["Utility reports", "Outage statistics", "Engineering standards"],
    status: "evidence_not_connected",
    futureWorkspace: "Grid reliability topic page with official utility source status.",
  },
  {
    topicId: "nuclear-safety-review",
    topicName: "Nuclear safety review",
    domain: "Energy",
    domainId: "energy",
    description: "Safety case methods, incident review, and regulatory evidence standards.",
    relatedMethods: ["Safety case review", "Probabilistic assessment", "Inspection protocols"],
    relatedEvidenceTypes: ["Regulatory filings", "Inspection reports", "Incident records"],
    status: "workspace_not_available",
    futureWorkspace: "Nuclear safety evidence review workspace.",
  },
  {
    topicId: "hydrogen-production",
    topicName: "Hydrogen production",
    domain: "Energy",
    domainId: "energy",
    description: "Production pathways, efficiency measurement, and infrastructure research.",
    relatedMethods: ["Electrolysis testing", "Process efficiency analysis", "Pilot evaluation"],
    relatedEvidenceTypes: ["Pilot data", "Process specifications", "Policy reports"],
    status: "catalog_available",
    futureWorkspace: "Hydrogen production topic page with methods and sources.",
  },
  // Materials Science
  {
    topicId: "nanomaterials",
    topicName: "Nanomaterials",
    domain: "Materials Science",
    domainId: "materials-science",
    description: "Nanoscale materials synthesis, characterization, and safety review methods.",
    relatedMethods: ["Electron microscopy", "Synthesis protocols", "Toxicity screening"],
    relatedEvidenceTypes: ["Characterization data", "Safety studies", "Methods papers"],
    status: "catalog_available",
    futureWorkspace: "Nanomaterials topic page with methods and evidence types.",
  },
  {
    topicId: "battery-electrolytes",
    topicName: "Battery electrolytes",
    domain: "Materials Science",
    domainId: "materials-science",
    description: "Electrolyte chemistry, stability testing, and materials compatibility research.",
    relatedMethods: ["Electrochemical testing", "Thermal analysis", "Compatibility screening"],
    relatedEvidenceTypes: ["Lab datasets", "Material specifications", "Patents"],
    status: "workspace_not_available",
    futureWorkspace: "Battery electrolytes evidence workspace.",
  },
  {
    topicId: "corrosion-resistance",
    topicName: "Corrosion resistance",
    domain: "Materials Science",
    domainId: "materials-science",
    description: "Corrosion mechanisms, protective coatings, and infrastructure longevity research.",
    relatedMethods: ["Accelerated testing", "Coating evaluation", "Field monitoring"],
    relatedEvidenceTypes: ["Test reports", "Material standards", "Inspection records"],
    status: "catalog_available",
    futureWorkspace: "Corrosion resistance topic page with engineering evidence.",
  },
  {
    topicId: "semiconductors",
    topicName: "Semiconductors",
    domain: "Materials Science",
    domainId: "materials-science",
    description: "Semiconductor materials, fabrication methods, and supply chain research.",
    relatedMethods: ["Wafer characterization", "Yield analysis", "Process monitoring"],
    relatedEvidenceTypes: ["Fab specifications", "Research datasets", "Industry reports"],
    status: "evidence_not_connected",
    futureWorkspace: "Semiconductor topic workspace with source connection status.",
  },
  {
    topicId: "biocompatible-materials",
    topicName: "Biocompatible materials",
    domain: "Materials Science",
    domainId: "materials-science",
    description: "Materials for medical devices, implants, and biological interface research.",
    relatedMethods: ["Biocompatibility testing", "Surface analysis", "Clinical correlation"],
    relatedEvidenceTypes: ["Test standards", "Clinical evaluations", "Regulatory submissions"],
    status: "workspace_not_available",
    futureWorkspace: "Biocompatible materials topic page with review methods.",
  },
  {
    topicId: "composite-structures",
    topicName: "Composite structures",
    domain: "Materials Science",
    domainId: "materials-science",
    description: "Composite design, failure analysis, and structural performance research.",
    relatedMethods: ["Mechanical testing", "Finite element modeling", "Fatigue analysis"],
    relatedEvidenceTypes: ["Test data", "Design standards", "Failure case studies"],
    status: "catalog_available",
    futureWorkspace: "Composite structures topic page with engineering evidence types.",
  },
  // Engineering
  {
    topicId: "structural-safety",
    topicName: "Structural safety",
    domain: "Engineering",
    domainId: "engineering",
    description: "Building and infrastructure safety assessment methods and standards.",
    relatedMethods: ["Structural analysis", "Inspection protocols", "Seismic assessment"],
    relatedEvidenceTypes: ["Engineering codes", "Inspection reports", "Test results"],
    status: "catalog_available",
    futureWorkspace: "Structural safety topic page with standards and open questions.",
  },
  {
    topicId: "water-infrastructure",
    topicName: "Water infrastructure",
    domain: "Engineering",
    domainId: "engineering",
    description: "Water supply, distribution systems, and infrastructure resilience research.",
    relatedMethods: ["Hydraulic modeling", "Asset inspection", "Failure mode analysis"],
    relatedEvidenceTypes: ["Infrastructure audits", "Engineering drawings", "Maintenance logs"],
    status: "catalog_available",
    futureWorkspace: "Water infrastructure topic workspace.",
  },
  {
    topicId: "robotics-systems",
    topicName: "Robotics systems",
    domain: "Engineering",
    domainId: "engineering",
    description: "Robotic design, control methods, and safety validation in applied settings.",
    relatedMethods: ["Control system testing", "Safety validation", "Human factors review"],
    relatedEvidenceTypes: ["Test protocols", "Safety standards", "Performance benchmarks"],
    status: "workspace_not_available",
    futureWorkspace: "Robotics systems topic page with methods and evidence types.",
  },
  {
    topicId: "aerospace-materials",
    topicName: "Aerospace materials",
    domain: "Engineering",
    domainId: "engineering",
    description: "Materials for aviation and space applications under extreme conditions.",
    relatedMethods: ["Fatigue testing", "Thermal cycling", "Nondestructive evaluation"],
    relatedEvidenceTypes: ["Qualification reports", "Material certifications", "Test datasets"],
    status: "evidence_not_connected",
    futureWorkspace: "Aerospace materials evidence review workspace.",
  },
  {
    topicId: "civil-resilience",
    topicName: "Civil resilience",
    domain: "Engineering",
    domainId: "engineering",
    description: "Infrastructure resilience to disasters, climate stress, and aging systems.",
    relatedMethods: ["Risk assessment", "Redundancy analysis", "Recovery planning"],
    relatedEvidenceTypes: ["Risk maps", "Damage assessments", "Recovery plans"],
    status: "catalog_available",
    futureWorkspace: "Civil resilience topic page with official engineering evidence.",
  },
  {
    topicId: "process-optimization",
    topicName: "Process optimization",
    domain: "Engineering",
    domainId: "engineering",
    description: "Industrial process efficiency, quality control, and operational research methods.",
    relatedMethods: ["Process mapping", "Statistical process control", "Simulation"],
    relatedEvidenceTypes: ["Operational data", "Quality records", "Process specifications"],
    status: "workspace_not_available",
    futureWorkspace: "Process optimization topic workspace.",
  },
  // Computer Science
  {
    topicId: "ai-safety",
    topicName: "AI safety",
    domain: "Computer Science",
    domainId: "computer-science",
    description: "Safety evaluation methods, alignment research, and governance questions for AI systems.",
    relatedMethods: ["Red teaming", "Evaluation benchmarks", "Risk assessment frameworks"],
    relatedEvidenceTypes: ["Evaluation reports", "Policy guidance", "Methods documentation"],
    status: "catalog_available",
    futureWorkspace: "AI safety topic page with methods, sources, and open questions.",
  },
  {
    topicId: "machine-learning-interpretability",
    topicName: "Machine learning interpretability",
    domain: "Computer Science",
    domainId: "computer-science",
    description: "Methods to explain model behavior and validate decisions in applied systems.",
    relatedMethods: ["Feature attribution", "Model auditing", "Human review protocols"],
    relatedEvidenceTypes: ["Audit reports", "Methods papers", "Evaluation datasets"],
    status: "workspace_not_available",
    futureWorkspace: "ML interpretability evidence review workspace.",
  },
  {
    topicId: "cryptography",
    topicName: "Cryptography",
    domain: "Computer Science",
    domainId: "computer-science",
    description: "Cryptographic protocols, security proofs, and implementation review methods.",
    relatedMethods: ["Security proofs", "Penetration testing", "Formal verification"],
    relatedEvidenceTypes: ["Standards documents", "Security audits", "Protocol specifications"],
    status: "catalog_available",
    futureWorkspace: "Cryptography topic page with standards and methods references.",
  },
  {
    topicId: "distributed-systems",
    topicName: "Distributed systems",
    domain: "Computer Science",
    domainId: "computer-science",
    description: "System design, consistency models, and reliability research for large-scale systems.",
    relatedMethods: ["Fault injection", "Consistency analysis", "Performance benchmarking"],
    relatedEvidenceTypes: ["Benchmark results", "Design documents", "Incident postmortems"],
    status: "catalog_available",
    futureWorkspace: "Distributed systems topic workspace.",
  },
  {
    topicId: "software-verification",
    topicName: "Software verification",
    domain: "Computer Science",
    domainId: "computer-science",
    description: "Formal and empirical methods for verifying software correctness and safety.",
    relatedMethods: ["Formal methods", "Unit testing", "Static analysis"],
    relatedEvidenceTypes: ["Verification reports", "Test suites", "Specification documents"],
    status: "workspace_not_available",
    futureWorkspace: "Software verification topic page with methods and evidence types.",
  },
  {
    topicId: "human-computer-interaction",
    topicName: "Human-computer interaction",
    domain: "Computer Science",
    domainId: "computer-science",
    description: "Usability research, accessibility methods, and interaction design evaluation.",
    relatedMethods: ["Usability testing", "Accessibility audits", "Eye-tracking studies"],
    relatedEvidenceTypes: ["Study protocols", "Usability findings", "Design guidelines"],
    status: "catalog_available",
    futureWorkspace: "HCI topic page with research methods and open questions.",
  },
  {
    topicId: "data-privacy-methods",
    topicName: "Data privacy methods",
    domain: "Computer Science",
    domainId: "computer-science",
    description: "Privacy-preserving computation, consent models, and regulatory compliance research.",
    relatedMethods: ["Privacy impact assessment", "Anonymization review", "Differential privacy"],
    relatedEvidenceTypes: ["Policy texts", "Technical standards", "Audit findings"],
    status: "evidence_not_connected",
    futureWorkspace: "Data privacy topic workspace with official source status.",
  },
  // Economics & Policy
  {
    topicId: "health-economics",
    topicName: "Health economics",
    domain: "Economics & Policy",
    domainId: "economics-policy",
    description: "Cost-effectiveness, health financing, and resource allocation research methods.",
    relatedMethods: ["Cost-effectiveness analysis", "Budget impact modeling", "Equity assessment"],
    relatedEvidenceTypes: ["Health accounts", "Economic evaluations", "Policy briefs"],
    status: "catalog_available",
    futureWorkspace: "Health economics topic page with official statistics references.",
  },
  {
    topicId: "climate-policy-modeling",
    topicName: "Climate policy modeling",
    domain: "Economics & Policy",
    domainId: "economics-policy",
    description: "Policy simulation, carbon pricing research, and transition pathway analysis.",
    relatedMethods: ["Integrated assessment", "Scenario modeling", "Sensitivity analysis"],
    relatedEvidenceTypes: ["Model documentation", "Policy proposals", "Emissions data"],
    status: "workspace_not_available",
    futureWorkspace: "Climate policy modeling evidence workspace.",
  },
  {
    topicId: "innovation-policy",
    topicName: "Innovation policy",
    domain: "Economics & Policy",
    domainId: "economics-policy",
    description: "R&D incentives, patent systems, and technology transfer policy research.",
    relatedMethods: ["Patent analysis", "R&D surveys", "Program evaluation"],
    relatedEvidenceTypes: ["Patent records", "R&D statistics", "Policy evaluations"],
    status: "catalog_available",
    futureWorkspace: "Innovation policy topic page with methods and sources.",
  },
  {
    topicId: "public-finance-review",
    topicName: "Public finance review",
    domain: "Economics & Policy",
    domainId: "economics-policy",
    description: "Government budgeting, fiscal transparency, and public spending analysis.",
    relatedMethods: ["Budget analysis", "Fiscal forecasting", "Expenditure tracking"],
    relatedEvidenceTypes: ["Budget documents", "Audit reports", "Official statistics"],
    status: "catalog_available",
    futureWorkspace: "Public finance topic workspace with official document references.",
  },
  {
    topicId: "trade-supply-chains",
    topicName: "Trade and supply chains",
    domain: "Economics & Policy",
    domainId: "economics-policy",
    description: "Trade flow analysis, supply chain mapping, and resilience policy research.",
    relatedMethods: ["Trade flow analysis", "Network mapping", "Disruption modeling"],
    relatedEvidenceTypes: ["Trade statistics", "Customs data", "Industry reports"],
    status: "evidence_not_connected",
    futureWorkspace: "Trade and supply chain topic page with source connection status.",
  },
  {
    topicId: "labor-market-research",
    topicName: "Labor market research",
    domain: "Economics & Policy",
    domainId: "economics-policy",
    description: "Employment trends, wage analysis, and workforce policy evaluation methods.",
    relatedMethods: ["Labor force surveys", "Wage analysis", "Policy impact review"],
    relatedEvidenceTypes: ["Labor statistics", "Survey microdata", "Policy reports"],
    status: "catalog_available",
    futureWorkspace: "Labor market topic page with official statistics and methods.",
  },
  // Social Sciences
  {
    topicId: "education-research",
    topicName: "Education research",
    domain: "Social Sciences",
    domainId: "social-sciences",
    description: "Learning outcomes, curriculum evaluation, and education policy research methods.",
    relatedMethods: ["Randomized field trials", "Longitudinal studies", "Assessment design"],
    relatedEvidenceTypes: ["Assessment data", "Policy documents", "Survey results"],
    status: "catalog_available",
    futureWorkspace: "Education research topic page with methods and evidence types.",
  },
  {
    topicId: "urban-development",
    topicName: "Urban development",
    domain: "Social Sciences",
    domainId: "social-sciences",
    description: "City planning, housing policy, and urban infrastructure social impact research.",
    relatedMethods: ["Spatial analysis", "Household surveys", "Policy comparison"],
    relatedEvidenceTypes: ["Census data", "Planning documents", "Survey datasets"],
    status: "workspace_not_available",
    futureWorkspace: "Urban development topic workspace.",
  },
  {
    topicId: "migration-studies",
    topicName: "Migration studies",
    domain: "Social Sciences",
    domainId: "social-sciences",
    description: "Migration patterns, integration research, and policy evidence review methods.",
    relatedMethods: ["Population registers", "Survey research", "Qualitative interviews"],
    relatedEvidenceTypes: ["Migration statistics", "Survey data", "Policy records"],
    status: "evidence_not_connected",
    futureWorkspace: "Migration studies topic page with official source status.",
  },
  {
    topicId: "behavioral-research-methods",
    topicName: "Behavioral research methods",
    domain: "Social Sciences",
    domainId: "social-sciences",
    description: "Experimental and observational methods for studying human behavior and decision-making.",
    relatedMethods: ["Controlled experiments", "Observational cohorts", "Survey design"],
    relatedEvidenceTypes: ["Study protocols", "Survey instruments", "Ethics approvals"],
    status: "catalog_available",
    futureWorkspace: "Behavioral methods topic page with open questions and sources.",
  },
  {
    topicId: "cultural-preservation",
    topicName: "Cultural preservation",
    domain: "Social Sciences",
    domainId: "social-sciences",
    description: "Heritage documentation, language preservation, and cultural policy research.",
    relatedMethods: ["Archival review", "Ethnographic documentation", "Community consultation"],
    relatedEvidenceTypes: ["Heritage registries", "Documentation archives", "Policy frameworks"],
    status: "catalog_available",
    futureWorkspace: "Cultural preservation topic workspace.",
  },
  {
    topicId: "governance-surveys",
    topicName: "Governance surveys",
    domain: "Social Sciences",
    domainId: "social-sciences",
    description: "Public administration surveys, institutional trust research, and governance metrics.",
    relatedMethods: ["Survey sampling", "Index construction", "Transparency scoring"],
    relatedEvidenceTypes: ["Survey datasets", "Administrative records", "Governance indices"],
    status: "workspace_not_available",
    futureWorkspace: "Governance surveys topic page with methods and evidence types.",
  },
] as const;

export function filterResearchTopics(
  topics: readonly ResearchTopic[],
  options: { query?: string; domainId?: ResearchDomainId | "all" },
): ResearchTopic[] {
  const normalizedQuery = options.query?.trim().toLowerCase() ?? "";

  return topics.filter((topic) => {
    const matchesDomain =
      !options.domainId || options.domainId === "all" || topic.domainId === options.domainId;

    if (!normalizedQuery) {
      return matchesDomain;
    }

    const haystack = [
      topic.topicName,
      topic.domain,
      topic.description,
      ...topic.relatedMethods,
      ...topic.relatedEvidenceTypes,
    ]
      .join(" ")
      .toLowerCase();

    return matchesDomain && haystack.includes(normalizedQuery);
  });
}

export function getResearchTopicCountByDomain(
  topics: readonly ResearchTopic[],
): Record<ResearchDomainId, number> {
  const counts = Object.fromEntries(
    RESEARCH_DOMAINS.map((d) => [d.domainId, 0]),
  ) as Record<ResearchDomainId, number>;

  for (const topic of topics) {
    counts[topic.domainId] += 1;
  }

  return counts;
}

export function getResearchTopicById(topicId: string): ResearchTopic | undefined {
  return RESEARCH_TOPICS.find((topic) => topic.topicId === topicId);
}

export function getResearchTopicPath(topicId: string): string {
  return `/research/${topicId}`;
}
